
    // This file is auto-generated by a script. Do not edit manually.
    // It is used to provide type-safe access to the backend tRPC API.

    import { inferRouterInputs, inferRouterOutputs } from '@trpc/server';
    import { AppRouter } from '../trpc/app-router';

    export type RouterInputs = inferRouterInputs<AppRouter>;
    export type RouterOutputs = inferRouterOutputs<AppRouter>;
  